export interface StdlibEntry {
  name: string;
  kind: "function" | "class" | "interface" | "object";
  detail: string;
  documentation: string;
}

const fn = (name: string, detail: string, documentation: string): StdlibEntry => ({ name, kind: "function", detail, documentation });
const cls = (name: string, documentation: string): StdlibEntry => ({ name, kind: "class", detail: `class ${name}`, documentation });
const iface = (name: string, documentation: string): StdlibEntry => ({ name, kind: "interface", detail: `interface ${name}`, documentation });

/** Commonly used declarations imported by default in every Kotlin/JVM file. */
export const STDLIB: readonly StdlibEntry[] = [
  fn("println", "fun println(message: Any?)", "Prints the given message and the line separator to the standard output stream."),
  fn("print", "fun print(message: Any?)", "Prints the given message to the standard output stream."),
  fn("readln", "fun readln(): String", "Reads a line of input from the standard input stream. Throws when end of input is reached."),
  fn("readlnOrNull", "fun readlnOrNull(): String?", "Reads a line of input from the standard input stream, or null at end of input."),
  fn("readLine", "fun readLine(): String?", "Reads a line of input from the standard input stream."),
  fn("listOf", "fun <T> listOf(vararg elements: T): List<T>", "Returns a new read only list of given elements."),
  fn("mutableListOf", "fun <T> mutableListOf(vararg elements: T): MutableList<T>", "Returns a new MutableList with the given elements."),
  fn("arrayListOf", "fun <T> arrayListOf(vararg elements: T): ArrayList<T>", "Returns a new ArrayList with the given elements."),
  fn("emptyList", "fun <T> emptyList(): List<T>", "Returns an empty read only list."),
  fn("listOfNotNull", "fun <T : Any> listOfNotNull(vararg elements: T?): List<T>", "Returns a new read only list only of those given elements, that are not null."),
  fn("buildList", "fun <E> buildList(builderAction: MutableList<E>.() -> Unit): List<E>", "Builds a new read only List by populating a MutableList."),
  fn("setOf", "fun <T> setOf(vararg elements: T): Set<T>", "Returns a new read only set with the given elements."),
  fn("mutableSetOf", "fun <T> mutableSetOf(vararg elements: T): MutableSet<T>", "Returns a new MutableSet with the given elements."),
  fn("hashSetOf", "fun <T> hashSetOf(vararg elements: T): HashSet<T>", "Returns a new HashSet with the given elements."),
  fn("emptySet", "fun <T> emptySet(): Set<T>", "Returns an empty read only set."),
  fn("buildSet", "fun <E> buildSet(builderAction: MutableSet<E>.() -> Unit): Set<E>", "Builds a new read only Set by populating a MutableSet."),
  fn("mapOf", "fun <K, V> mapOf(vararg pairs: Pair<K, V>): Map<K, V>", "Returns a new read only map with the specified contents."),
  fn("mutableMapOf", "fun <K, V> mutableMapOf(vararg pairs: Pair<K, V>): MutableMap<K, V>", "Returns a new MutableMap with the specified contents."),
  fn("hashMapOf", "fun <K, V> hashMapOf(vararg pairs: Pair<K, V>): HashMap<K, V>", "Returns a new HashMap with the specified contents."),
  fn("emptyMap", "fun <K, V> emptyMap(): Map<K, V>", "Returns an empty read only map."),
  fn("buildMap", "fun <K, V> buildMap(builderAction: MutableMap<K, V>.() -> Unit): Map<K, V>", "Builds a new read only Map by populating a MutableMap."),
  fn("arrayOf", "fun <T> arrayOf(vararg elements: T): Array<T>", "Returns an array containing the specified elements."),
  fn("arrayOfNulls", "fun <T> arrayOfNulls(size: Int): Array<T?>", "Returns an array of objects of the given type with the given size, initialized with null values."),
  fn("emptyArray", "fun <T> emptyArray(): Array<T>", "Returns an empty array of the specified type T."),
  fn("intArrayOf", "fun intArrayOf(vararg elements: Int): IntArray", "Returns an array containing the specified Int numbers."),
  fn("longArrayOf", "fun longArrayOf(vararg elements: Long): LongArray", "Returns an array containing the specified Long numbers."),
  fn("doubleArrayOf", "fun doubleArrayOf(vararg elements: Double): DoubleArray", "Returns an array containing the specified Double numbers."),
  fn("charArrayOf", "fun charArrayOf(vararg elements: Char): CharArray", "Returns an array containing the specified characters."),
  fn("booleanArrayOf", "fun booleanArrayOf(vararg elements: Boolean): BooleanArray", "Returns an array containing the specified boolean values."),
  fn("sequenceOf", "fun <T> sequenceOf(vararg elements: T): Sequence<T>", "Creates a sequence that returns the specified values."),
  fn("generateSequence", "fun <T : Any> generateSequence(seed: T?, nextFunction: (T) -> T?): Sequence<T>", "Returns a sequence defined by the starting value seed and the function nextFunction."),
  fn("sequence", "fun <T> sequence(block: suspend SequenceScope<T>.() -> Unit): Sequence<T>", "Builds a Sequence lazily yielding values one by one."),
  fn("buildString", "fun buildString(builderAction: StringBuilder.() -> Unit): String", "Builds a new string by populating a newly created StringBuilder."),
  fn("repeat", "fun repeat(times: Int, action: (Int) -> Unit)", "Executes the given function action specified number of times."),
  fn("require", "fun require(value: Boolean, lazyMessage: () -> Any)", "Throws an IllegalArgumentException if the value is false."),
  fn("requireNotNull", "fun <T : Any> requireNotNull(value: T?): T", "Throws an IllegalArgumentException if the value is null. Otherwise returns the not null value."),
  fn("check", "fun check(value: Boolean, lazyMessage: () -> Any)", "Throws an IllegalStateException if the value is false."),
  fn("checkNotNull", "fun <T : Any> checkNotNull(value: T?): T", "Throws an IllegalStateException if the value is null. Otherwise returns the not null value."),
  fn("error", "fun error(message: Any): Nothing", "Throws an IllegalStateException with the given message."),
  fn("TODO", "fun TODO(reason: String): Nothing", "Always throws NotImplementedError stating that operation is not implemented."),
  fn("run", "fun <R> run(block: () -> R): R", "Calls the specified function block and returns its result."),
  fn("with", "fun <T, R> with(receiver: T, block: T.() -> R): R", "Calls the specified function block with the given receiver as its receiver and returns its result."),
  fn("let", "fun <T, R> T.let(block: (T) -> R): R", "Calls the specified function block with this value as its argument and returns its result."),
  fn("also", "fun <T> T.also(block: (T) -> Unit): T", "Calls the specified function block with this value as its argument and returns this value."),
  fn("apply", "fun <T> T.apply(block: T.() -> Unit): T", "Calls the specified function block with this value as its receiver and returns this value."),
  fn("takeIf", "fun <T> T.takeIf(predicate: (T) -> Boolean): T?", "Returns this value if it satisfies the given predicate or null, if it does not."),
  fn("takeUnless", "fun <T> T.takeUnless(predicate: (T) -> Boolean): T?", "Returns this value if it does not satisfy the given predicate or null, if it does."),
  fn("lazy", "fun <T> lazy(initializer: () -> T): Lazy<T>", "Creates a new instance of the Lazy that uses the specified initialization function."),
  fn("runCatching", "fun <R> runCatching(block: () -> R): Result<R>", "Calls the specified function block and returns its encapsulated result if invocation was successful, catching any Throwable exception."),
  fn("maxOf", "fun <T : Comparable<T>> maxOf(a: T, b: T): T", "Returns the greater of two values."),
  fn("minOf", "fun <T : Comparable<T>> minOf(a: T, b: T): T", "Returns the smaller of two values."),
  fn("assert", "fun assert(value: Boolean)", "Throws an AssertionError if the value is false and runtime assertions have been enabled on the JVM."),
  fn("synchronized", "fun <R> synchronized(lock: Any, block: () -> R): R", "Executes the given function block while holding the monitor of the given object lock."),
  cls("Any", "The root of the Kotlin class hierarchy."),
  cls("Unit", "The type with only one value: the Unit object."),
  cls("Nothing", "Nothing has no instances. Represents a value that never exists."),
  cls("String", "The String class represents character strings."),
  cls("Char", "Represents a 16 bit Unicode character."),
  cls("Boolean", "Represents a value which is either true or false."),
  cls("Byte", "Represents an 8 bit signed integer."),
  cls("Short", "Represents a 16 bit signed integer."),
  cls("Int", "Represents a 32 bit signed integer."),
  cls("Long", "Represents a 64 bit signed integer."),
  cls("Float", "Represents a single precision 32 bit IEEE 754 floating point number."),
  cls("Double", "Represents a double precision 64 bit IEEE 754 floating point number."),
  cls("UInt", "Represents a 32 bit unsigned integer."),
  cls("ULong", "Represents a 64 bit unsigned integer."),
  cls("Array", "Represents an array."),
  cls("IntArray", "An array of ints."),
  cls("LongArray", "An array of longs."),
  cls("DoubleArray", "An array of doubles."),
  cls("CharArray", "An array of chars."),
  cls("BooleanArray", "An array of booleans."),
  cls("ByteArray", "An array of bytes."),
  cls("Pair", "Represents a generic pair of two values."),
  cls("Triple", "Represents a triad of values."),
  cls("Result", "A discriminated union that encapsulates a successful outcome or a failure with a Throwable."),
  cls("StringBuilder", "A mutable sequence of characters."),
  cls("Regex", "Represents a compiled regular expression."),
  cls("IntRange", "A range of values of type Int."),
  cls("LongRange", "A range of values of type Long."),
  cls("CharRange", "A range of values of type Char."),
  cls("ArrayList", "Resizable array implementation of MutableList."),
  cls("HashMap", "Hash table based implementation of MutableMap."),
  cls("LinkedHashMap", "Hash table based implementation of MutableMap with predictable iteration order."),
  cls("HashSet", "Hash table based implementation of MutableSet."),
  cls("LinkedHashSet", "Hash table based implementation of MutableSet with predictable iteration order."),
  cls("Throwable", "The base class for all errors and exceptions."),
  cls("Exception", "The base class for exceptions that applications might want to catch."),
  cls("RuntimeException", "Exception thrown during the normal operation of the JVM."),
  cls("Error", "An Error indicates serious problems that an application should not try to catch."),
  cls("IllegalArgumentException", "Thrown to indicate that a method has been passed an illegal or inappropriate argument."),
  cls("IllegalStateException", "Signals that a method has been invoked at an illegal or inappropriate time."),
  cls("IndexOutOfBoundsException", "Thrown to indicate that an index of some sort is out of range."),
  cls("NoSuchElementException", "Thrown to indicate that the element being requested does not exist."),
  cls("NullPointerException", "Thrown when an application attempts to use null where an object is required."),
  cls("UnsupportedOperationException", "Thrown to indicate that the requested operation is not supported."),
  cls("ArithmeticException", "Thrown when an exceptional arithmetic condition has occurred."),
  cls("NumberFormatException", "Thrown when converting a string to a numeric type fails."),
  cls("NotImplementedError", "Thrown by TODO() to indicate that an operation is not implemented."),
  iface("Comparable", "Classes which inherit from this interface have a defined total ordering between their instances."),
  iface("Comparator", "Provides a comparison function for imposing a total ordering between instances of the type."),
  iface("Iterable", "Classes that inherit from this interface can be represented as a sequence of elements that can be iterated over."),
  iface("Iterator", "An iterator over a collection or another entity that can be represented as a sequence of elements."),
  iface("Collection", "A generic collection of elements."),
  iface("MutableCollection", "A generic collection of elements that supports adding and removing elements."),
  iface("List", "A generic ordered collection of elements."),
  iface("MutableList", "A generic ordered collection of elements that supports adding and removing elements."),
  iface("Set", "A generic unordered collection of elements that does not support duplicate elements."),
  iface("MutableSet", "A generic unordered collection of elements that does not support duplicate elements, and supports adding and removing elements."),
  iface("Map", "A collection that holds pairs of objects (keys and values) and supports efficiently retrieving the value corresponding to each key."),
  iface("MutableMap", "A modifiable collection that holds pairs of objects (keys and values)."),
  iface("Sequence", "A sequence that returns values through its iterator. The values are evaluated lazily."),
  iface("CharSequence", "Represents a readable sequence of Char values."),
  iface("Lazy", "Represents a value with lazy initialization."),
  iface("Runnable", "Represents a command that can be executed."),
];
