/**
 * Members of common standard library types, written as Kotlin signatures.
 * `fun name(params): Return` and `val name: Type`; the return type drives chained completion.
 */
export type MemberTable = Readonly<Record<string, readonly string[]>>;

/** Operations shared by everything iterable. `L` is the type that transforming operations return. */
function iterableOps(L: "List" | "Sequence"): string[] {
  return [
    `fun map(transform: (T) -> R): ${L}<R>`,
    `fun mapIndexed(transform: (Int, T) -> R): ${L}<R>`,
    `fun mapNotNull(transform: (T) -> R?): ${L}<R>`,
    `fun flatMap(transform: (T) -> Iterable<R>): ${L}<R>`,
    `fun filter(predicate: (T) -> Boolean): ${L}<T>`,
    `fun filterNot(predicate: (T) -> Boolean): ${L}<T>`,
    `fun filterNotNull(): ${L}<T>`,
    `fun filterIsInstance(): ${L}<R>`,
    `fun forEach(action: (T) -> Unit)`,
    `fun forEachIndexed(action: (Int, T) -> Unit)`,
    `fun onEach(action: (T) -> Unit): ${L}<T>`,
    `fun any(predicate: (T) -> Boolean): Boolean`,
    `fun all(predicate: (T) -> Boolean): Boolean`,
    `fun none(predicate: (T) -> Boolean): Boolean`,
    `fun count(predicate: (T) -> Boolean): Int`,
    `fun find(predicate: (T) -> Boolean): T?`,
    `fun first(): T`,
    `fun firstOrNull(): T?`,
    `fun last(): T`,
    `fun lastOrNull(): T?`,
    `fun single(): T`,
    `fun singleOrNull(): T?`,
    `fun elementAt(index: Int): T`,
    `fun elementAtOrNull(index: Int): T?`,
    `fun sum(): Int`,
    `fun sumOf(selector: (T) -> Int): Int`,
    `fun average(): Double`,
    `fun maxOrNull(): T?`,
    `fun minOrNull(): T?`,
    `fun maxByOrNull(selector: (T) -> R): T?`,
    `fun minByOrNull(selector: (T) -> R): T?`,
    `fun maxOf(selector: (T) -> R): R`,
    `fun minOf(selector: (T) -> R): R`,
    `fun sorted(): ${L}<T>`,
    `fun sortedDescending(): ${L}<T>`,
    `fun sortedBy(selector: (T) -> R?): ${L}<T>`,
    `fun sortedByDescending(selector: (T) -> R?): ${L}<T>`,
    `fun sortedWith(comparator: Comparator<T>): ${L}<T>`,
    `fun distinct(): ${L}<T>`,
    `fun distinctBy(selector: (T) -> K): ${L}<T>`,
    `fun take(n: Int): ${L}<T>`,
    `fun takeWhile(predicate: (T) -> Boolean): ${L}<T>`,
    `fun drop(n: Int): ${L}<T>`,
    `fun dropWhile(predicate: (T) -> Boolean): ${L}<T>`,
    `fun chunked(size: Int): ${L}<List<T>>`,
    `fun windowed(size: Int): ${L}<List<T>>`,
    `fun zip(other: Iterable<R>): ${L}<Pair<T, R>>`,
    `fun plus(element: T): ${L}<T>`,
    `fun minus(element: T): ${L}<T>`,
    `fun withIndex(): ${L}<IndexedValue<T>>`,
    `fun groupBy(keySelector: (T) -> K): Map<K, List<T>>`,
    `fun associate(transform: (T) -> Pair<K, V>): Map<K, V>`,
    `fun associateBy(keySelector: (T) -> K): Map<K, T>`,
    `fun associateWith(valueSelector: (T) -> V): Map<T, V>`,
    `fun partition(predicate: (T) -> Boolean): Pair<List<T>, List<T>>`,
    `fun fold(initial: R, operation: (R, T) -> R): R`,
    `fun reduce(operation: (T, T) -> T): T`,
    `fun joinToString(separator: CharSequence = ", "): String`,
    `fun contains(element: T): Boolean`,
    `fun toList(): List<T>`,
    `fun toMutableList(): MutableList<T>`,
    `fun toSet(): Set<T>`,
    `fun toMutableSet(): MutableSet<T>`,
    `fun asSequence(): Sequence<T>`,
    `fun reversed(): ${L}<T>`,
    `fun shuffled(): ${L}<T>`,
    `fun random(): T`,
    `fun iterator(): Iterator<T>`,
  ];
}

const COLLECTION = [
  `val size: Int`,
  `val indices: IntRange`,
  `val lastIndex: Int`,
  `fun isEmpty(): Boolean`,
  `fun isNotEmpty(): Boolean`,
  `fun indexOf(element: T): Int`,
  `fun lastIndexOf(element: T): Int`,
  `fun getOrNull(index: Int): T?`,
  `fun getOrElse(index: Int, defaultValue: (Int) -> T): T`,
  `fun ifEmpty(defaultValue: () -> R): List<T>`,
  `fun flatten(): List<R>`,
  `fun containsAll(elements: Collection<T>): Boolean`,
  ...iterableOps("List"),
];

export const MEMBERS: MemberTable = {
  Any: [
    "fun toString(): String",
    "fun equals(other: Any?): Boolean",
    "fun hashCode(): Int",
  ],
  CharSequence: [
    "val length: Int",
    "val lastIndex: Int",
    "val indices: IntRange",
    "fun get(index: Int): Char",
    "fun isEmpty(): Boolean",
    "fun isNotEmpty(): Boolean",
    "fun isBlank(): Boolean",
    "fun isNotBlank(): Boolean",
    "fun contains(other: CharSequence): Boolean",
    "fun startsWith(prefix: String): Boolean",
    "fun endsWith(suffix: String): Boolean",
    "fun indexOf(string: String): Int",
    "fun lastIndexOf(string: String): Int",
    "fun first(): Char",
    "fun firstOrNull(): Char?",
    "fun last(): Char",
    "fun lastOrNull(): Char?",
    "fun count(predicate: (Char) -> Boolean): Int",
    "fun any(predicate: (Char) -> Boolean): Boolean",
    "fun all(predicate: (Char) -> Boolean): Boolean",
    "fun none(predicate: (Char) -> Boolean): Boolean",
    "fun forEach(action: (Char) -> Unit)",
    "fun filter(predicate: (Char) -> Boolean): String",
    "fun map(transform: (Char) -> R): List<R>",
    "fun take(n: Int): String",
    "fun takeLast(n: Int): String",
    "fun drop(n: Int): String",
    "fun dropLast(n: Int): String",
    "fun substring(startIndex: Int): String",
    "fun trim(): String",
    "fun trimStart(): String",
    "fun trimEnd(): String",
    "fun reversed(): String",
    "fun lines(): List<String>",
    "fun split(delimiter: String): List<String>",
    "fun chunked(size: Int): List<String>",
    "fun windowed(size: Int): List<String>",
    "fun toList(): List<Char>",
    "fun toSet(): Set<Char>",
    "fun asSequence(): Sequence<Char>",
    "fun padStart(length: Int): String",
    "fun padEnd(length: Int): String",
    "fun repeat(n: Int): String",
    "fun toRegex(): Regex",
  ],
  String: [
    "fun uppercase(): String",
    "fun lowercase(): String",
    "fun substring(startIndex: Int, endIndex: Int): String",
    "fun substringBefore(delimiter: String): String",
    "fun substringAfter(delimiter: String): String",
    "fun substringBeforeLast(delimiter: String): String",
    "fun substringAfterLast(delimiter: String): String",
    "fun replace(oldValue: String, newValue: String): String",
    "fun replaceFirst(oldValue: String, newValue: String): String",
    "fun replaceFirstChar(transform: (Char) -> Char): String",
    "fun removePrefix(prefix: CharSequence): String",
    "fun removeSuffix(suffix: CharSequence): String",
    "fun trimIndent(): String",
    "fun trimMargin(): String",
    "fun toInt(): Int",
    "fun toIntOrNull(): Int?",
    "fun toLong(): Long",
    "fun toLongOrNull(): Long?",
    "fun toDouble(): Double",
    "fun toDoubleOrNull(): Double?",
    "fun toFloat(): Float",
    "fun toBoolean(): Boolean",
    "fun toCharArray(): Array<Char>",
    "fun format(vararg args: Any?): String",
    "fun compareTo(other: String): Int",
    "fun equals(other: String?, ignoreCase: Boolean = false): Boolean",
    "fun capitalize(): String",
    "fun plus(other: Any?): String",
  ],
  Number: [
    "fun toInt(): Int",
    "fun toLong(): Long",
    "fun toDouble(): Double",
    "fun toFloat(): Float",
    "fun toShort(): Short",
    "fun toByte(): Byte",
    "fun toChar(): Char",
    "fun compareTo(other: Int): Int",
  ],
  Int: [
    "val absoluteValue: Int",
    "val sign: Int",
    "fun coerceIn(minimumValue: Int, maximumValue: Int): Int",
    "fun coerceAtLeast(minimumValue: Int): Int",
    "fun coerceAtMost(maximumValue: Int): Int",
    "fun until(to: Int): IntRange",
    "fun downTo(to: Int): IntProgression",
    "fun rangeTo(other: Int): IntRange",
    "fun plus(other: Int): Int",
    "fun minus(other: Int): Int",
    "fun times(other: Int): Int",
    "fun div(other: Int): Int",
    "fun rem(other: Int): Int",
    "fun inc(): Int",
    "fun dec(): Int",
    "fun shl(bitCount: Int): Int",
    "fun shr(bitCount: Int): Int",
    "fun and(other: Int): Int",
    "fun or(other: Int): Int",
    "fun xor(other: Int): Int",
    "fun inv(): Int",
    "fun toString(radix: Int): String",
    "fun countOneBits(): Int",
  ],
  Long: [
    "val absoluteValue: Long",
    "val sign: Int",
    "fun coerceIn(minimumValue: Long, maximumValue: Long): Long",
    "fun coerceAtLeast(minimumValue: Long): Long",
    "fun coerceAtMost(maximumValue: Long): Long",
    "fun until(to: Long): LongRange",
    "fun downTo(to: Long): LongProgression",
    "fun rangeTo(other: Long): LongRange",
    "fun plus(other: Long): Long",
    "fun minus(other: Long): Long",
    "fun times(other: Long): Long",
    "fun div(other: Long): Long",
    "fun rem(other: Long): Long",
    "fun inc(): Long",
    "fun dec(): Long",
    "fun shl(bitCount: Int): Long",
    "fun shr(bitCount: Int): Long",
    "fun and(other: Long): Long",
    "fun or(other: Long): Long",
    "fun xor(other: Long): Long",
    "fun toString(radix: Int): String",
  ],
  Double: [
    "val absoluteValue: Double",
    "val sign: Double",
    "fun isNaN(): Boolean",
    "fun isInfinite(): Boolean",
    "fun isFinite(): Boolean",
    "fun roundToInt(): Int",
    "fun roundToLong(): Long",
    "fun coerceIn(minimumValue: Double, maximumValue: Double): Double",
    "fun coerceAtLeast(minimumValue: Double): Double",
    "fun coerceAtMost(maximumValue: Double): Double",
    "fun plus(other: Double): Double",
    "fun minus(other: Double): Double",
    "fun times(other: Double): Double",
    "fun div(other: Double): Double",
    "fun rem(other: Double): Double",
  ],
  Float: [
    "val absoluteValue: Float",
    "fun isNaN(): Boolean",
    "fun roundToInt(): Int",
    "fun coerceIn(minimumValue: Float, maximumValue: Float): Float",
  ],
  Boolean: [
    "fun not(): Boolean",
    "fun and(other: Boolean): Boolean",
    "fun or(other: Boolean): Boolean",
    "fun xor(other: Boolean): Boolean",
    "fun compareTo(other: Boolean): Int",
  ],
  Char: [
    "val code: Int",
    "fun isDigit(): Boolean",
    "fun isLetter(): Boolean",
    "fun isLetterOrDigit(): Boolean",
    "fun isUpperCase(): Boolean",
    "fun isLowerCase(): Boolean",
    "fun isWhitespace(): Boolean",
    "fun uppercase(): String",
    "fun lowercase(): String",
    "fun uppercaseChar(): Char",
    "fun lowercaseChar(): Char",
    "fun digitToInt(): Int",
    "fun digitToIntOrNull(): Int?",
    "fun plus(other: Int): Char",
    "fun minus(other: Char): Int",
    "fun compareTo(other: Char): Int",
    "fun toInt(): Int",
  ],
  Iterable: iterableOps("List"),
  Collection: COLLECTION,
  List: [
    "fun get(index: Int): T",
    "fun subList(fromIndex: Int, toIndex: Int): List<T>",
    "fun listIterator(): ListIterator<T>",
    ...COLLECTION,
  ],
  MutableList: [
    "fun add(element: T): Boolean",
    "fun addAll(elements: Collection<T>): Boolean",
    "fun remove(element: T): Boolean",
    "fun removeAt(index: Int): T",
    "fun removeAll(elements: Collection<T>): Boolean",
    "fun removeIf(filter: (T) -> Boolean): Boolean",
    "fun removeFirst(): T",
    "fun removeLast(): T",
    "fun retainAll(elements: Collection<T>): Boolean",
    "fun set(index: Int, element: T): T",
    "fun clear()",
    "fun sort()",
    "fun sortBy(selector: (T) -> R?)",
    "fun sortByDescending(selector: (T) -> R?)",
    "fun sortWith(comparator: Comparator<T>)",
    "fun sortDescending()",
    "fun shuffle()",
    "fun reverse()",
    "fun addFirst(element: T)",
    "fun addLast(element: T)",
  ],
  Set: COLLECTION,
  MutableSet: [
    "fun add(element: T): Boolean",
    "fun addAll(elements: Collection<T>): Boolean",
    "fun remove(element: T): Boolean",
    "fun removeAll(elements: Collection<T>): Boolean",
    "fun retainAll(elements: Collection<T>): Boolean",
    "fun clear()",
  ],
  Array: [
    "fun get(index: Int): T",
    "fun set(index: Int, value: T)",
    "fun copyOf(): Array<T>",
    "fun copyOfRange(fromIndex: Int, toIndex: Int): Array<T>",
    "fun fill(element: T)",
    "fun sort()",
    "fun sortDescending()",
    "fun contentToString(): String",
    "fun contentEquals(other: Array<T>): Boolean",
    ...COLLECTION,
  ],
  IntRange: [
    "val first: Int",
    "val last: Int",
    "fun step(step: Int): IntProgression",
    "fun contains(value: Int): Boolean",
    ...COLLECTION,
  ],
  Sequence: [
    "fun toList(): List<T>",
    "fun take(n: Int): Sequence<T>",
    ...iterableOps("Sequence"),
  ],
  Map: [
    "val size: Int",
    "val keys: Set<K>",
    "val values: List<V>",
    "val entries: Set<Map.Entry<K, V>>",
    "fun get(key: K): V?",
    "fun getOrDefault(key: K, defaultValue: V): V",
    "fun getOrElse(key: K, defaultValue: () -> V): V",
    "fun getValue(key: K): V",
    "fun containsKey(key: K): Boolean",
    "fun containsValue(value: V): Boolean",
    "fun isEmpty(): Boolean",
    "fun isNotEmpty(): Boolean",
    "fun forEach(action: (Map.Entry<K, V>) -> Unit)",
    "fun map(transform: (Map.Entry<K, V>) -> R): List<R>",
    "fun mapValues(transform: (Map.Entry<K, V>) -> R): Map<K, R>",
    "fun mapKeys(transform: (Map.Entry<K, V>) -> R): Map<R, V>",
    "fun filter(predicate: (Map.Entry<K, V>) -> Boolean): Map<K, V>",
    "fun filterKeys(predicate: (K) -> Boolean): Map<K, V>",
    "fun filterValues(predicate: (V) -> Boolean): Map<K, V>",
    "fun count(predicate: (Map.Entry<K, V>) -> Boolean): Int",
    "fun any(predicate: (Map.Entry<K, V>) -> Boolean): Boolean",
    "fun all(predicate: (Map.Entry<K, V>) -> Boolean): Boolean",
    "fun none(predicate: (Map.Entry<K, V>) -> Boolean): Boolean",
    "fun maxByOrNull(selector: (Map.Entry<K, V>) -> R): Map.Entry<K, V>?",
    "fun minByOrNull(selector: (Map.Entry<K, V>) -> R): Map.Entry<K, V>?",
    "fun toList(): List<Pair<K, V>>",
    "fun toMutableMap(): MutableMap<K, V>",
    "fun toSortedMap(): Map<K, V>",
    "fun plus(pair: Pair<K, V>): Map<K, V>",
    "fun minus(key: K): Map<K, V>",
  ],
  MutableMap: [
    "fun put(key: K, value: V): V?",
    "fun putAll(from: Map<K, V>)",
    "fun putIfAbsent(key: K, value: V): V?",
    "fun getOrPut(key: K, defaultValue: () -> V): V",
    "fun remove(key: K): V?",
    "fun clear()",
    "fun set(key: K, value: V)",
  ],
  Pair: [
    "val first: A",
    "val second: B",
    "fun toList(): List<R>",
    "fun component1(): A",
    "fun component2(): B",
    "fun copy(): Pair<A, B>",
  ],
  Result: [
    "val isSuccess: Boolean",
    "val isFailure: Boolean",
    "fun getOrNull(): T?",
    "fun getOrThrow(): T",
    "fun getOrDefault(defaultValue: T): T",
    "fun getOrElse(onFailure: (Throwable) -> T): T",
    "fun exceptionOrNull(): Throwable?",
    "fun map(transform: (T) -> R): Result<R>",
    "fun onSuccess(action: (T) -> Unit): Result<T>",
    "fun onFailure(action: (Throwable) -> Unit): Result<T>",
    "fun fold(onSuccess: (T) -> R, onFailure: (Throwable) -> R): R",
  ],
  Regex: [
    "val pattern: String",
    "fun matches(input: CharSequence): Boolean",
    "fun containsMatchIn(input: CharSequence): Boolean",
    "fun find(input: CharSequence): MatchResult?",
    "fun findAll(input: CharSequence): Sequence<MatchResult>",
    "fun matchEntire(input: CharSequence): MatchResult?",
    "fun replace(input: CharSequence, replacement: String): String",
    "fun split(input: CharSequence): List<String>",
  ],
  MatchResult: [
    "val value: String",
    "val groupValues: List<String>",
    "val range: IntRange",
    "fun next(): MatchResult?",
  ],
  StringBuilder: [
    "val length: Int",
    "fun append(value: Any?): StringBuilder",
    "fun appendLine(value: Any?): StringBuilder",
    "fun insert(index: Int, value: Any?): StringBuilder",
    "fun delete(startIndex: Int, endIndex: Int): StringBuilder",
    "fun deleteCharAt(index: Int): StringBuilder",
    "fun reverse(): StringBuilder",
    "fun clear(): StringBuilder",
    "fun setLength(newLength: Int)",
    "fun isEmpty(): Boolean",
    "fun isNotEmpty(): Boolean",
    "fun indexOf(string: String): Int",
    "fun substring(startIndex: Int): String",
    "fun toString(): String",
  ],
};

/** Supertypes whose members a type also has (listed from most to least specific). */
export const EXTENDS: Readonly<Record<string, readonly string[]>> = {
  String: ["CharSequence"],
  StringBuilder: ["CharSequence"],
  Int: ["Number"],
  Long: ["Number"],
  Double: ["Number"],
  Float: ["Number"],
  Short: ["Number"],
  Byte: ["Number"],
  MutableList: ["List"],
  MutableSet: ["Set"],
  MutableMap: ["Map"],
  List: ["Collection"],
  Set: ["Collection"],
  Collection: ["Iterable"],
  IntRange: ["Iterable"],
  Array: ["Iterable"],
};

/** Other spellings of the types above. */
export const TYPE_ALIASES: Readonly<Record<string, string>> = {
  ArrayList: "MutableList",
  LinkedList: "MutableList",
  HashSet: "MutableSet",
  LinkedHashSet: "MutableSet",
  TreeSet: "MutableSet",
  HashMap: "MutableMap",
  LinkedHashMap: "MutableMap",
  TreeMap: "MutableMap",
  IntArray: "Array",
  LongArray: "Array",
  DoubleArray: "Array",
  CharArray: "Array",
  BooleanArray: "Array",
  ByteArray: "Array",
  LongRange: "IntRange",
  CharRange: "IntRange",
  IntProgression: "IntRange",
  LongProgression: "IntRange",
  Short: "Int",
  Byte: "Int",
};

/** Result type of well known top level functions. */
export const FUNCTION_RETURNS: Readonly<Record<string, string>> = {
  listOf: "List",
  emptyList: "List",
  listOfNotNull: "List",
  buildList: "List",
  mutableListOf: "MutableList",
  arrayListOf: "MutableList",
  setOf: "Set",
  emptySet: "Set",
  buildSet: "Set",
  mutableSetOf: "MutableSet",
  hashSetOf: "MutableSet",
  linkedSetOf: "MutableSet",
  mapOf: "Map",
  emptyMap: "Map",
  buildMap: "Map",
  mutableMapOf: "MutableMap",
  hashMapOf: "MutableMap",
  linkedMapOf: "MutableMap",
  arrayOf: "Array",
  emptyArray: "Array",
  arrayOfNulls: "Array",
  intArrayOf: "Array",
  longArrayOf: "Array",
  doubleArrayOf: "Array",
  charArrayOf: "Array",
  booleanArrayOf: "Array",
  sequenceOf: "Sequence",
  sequence: "Sequence",
  generateSequence: "Sequence",
  readln: "String",
  readLine: "String",
  readlnOrNull: "String",
  buildString: "String",
  StringBuilder: "StringBuilder",
  Regex: "Regex",
  Pair: "Pair",
  runCatching: "Result",
  maxOf: "Int",
  minOf: "Int",
};
